import React from "react";
import { ShieldCheck, Leaf, BookCheck } from "lucide-react";

const points = [
  {
    icon: ShieldCheck,
    title: "Smart Contract Audits",
    description:
      "All smart contracts undergo rigorous third-party audits before deployment to ensure security and eliminate vulnerabilities.",
  },
  {
    icon: Leaf,
    title: "Eco Impact Ledger",
    description:
      "We actively track and report the positive environmental impact, including paper and CO₂ savings, generated by the ecosystem.",
  },
  {
    icon: BookCheck,
    title: "Data & Privacy Compliance",
    description:
      "Our platform is designed for GDPR and NDPR compliance, ensuring end-to-end encryption for all user and transaction data.",
  },
];

const SecurityEco = () => {
  return (
    <section className="py-20 bg-slate-900/50">
      <div className="container mx-auto px-6">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-white">
            Security, Compliance & Sustainability
          </h2>
          <p className="text-slate-400 mt-4 max-w-2xl mx-auto">
            Trust and transparency are at the core of our architecture. We are
            committed to building a secure and sustainable ecosystem.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {points.map((point, index) => (
            <div
              key={index}
              className="text-center p-6 bg-slate-800 rounded-lg"
            >
              <div className="flex justify-center mb-4">
                <div className="bg-slate-700 p-4 rounded-full">
                  <point.icon className="text-cyan-400" size={32} />
                </div>
              </div>
              <h3 className="text-xl font-bold text-white mb-2">
                {point.title}
              </h3>
              <p className="text-slate-400">{point.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default SecurityEco;
